Add side menu component
CyberSlug322/beer-catalog pull request #21
Opened 2022-03-28 17:17 UTC by CyberSlug322

2022-03-29 08:49 UTC, anton-matseichyk requested changes

2022-03-29 08:49 UTC, anton-matseichyk commented on src/containers/sideMenu/SideMenuBlock.scss
> +.side-menu-block {
I don't think we need this interim component. These styles are positioning, so they belong to .layout__side-menu

2022-03-29 08:49 UTC, anton-matseichyk commented on src/containers/sideMenu/SideMenuBlock.jsx
> +export const SideMenuBlock = ({onMenuButtonClick}) => (
onOutsideClick

2022-03-29 08:49 UTC, anton-matseichyk commented on src/containers/sideMenu/SideMenuBlock.jsx
> +export const SideMenuBlock = ({onMenuButtonClick}) => (
Check event.target and event.relatedTarget(?) to figure out whether div itself or child was clicked

2022-03-29 23:49 UTC, CyberSlug322 commented on src/containers/sideMenu/SideMenuBlock.scss
> +.side-menu-block {
should i the whole component SideMenuBlock or move css styles to layout is enought?

2022-03-30 00:11 UTC, CyberSlug322 commented on src/containers/sideMenu/SideMenuBlock.jsx
> +export const SideMenuBlock = ({onMenuButtonClick}) => (
i used stopPropagation() is it fine?

2022-03-30 21:18 UTC, anton-matseichyk requested changes

2022-03-30 21:18 UTC, anton-matseichyk commented on src/containers/sideMenu/SideMenuBlock.scss
> +    position: absolute;
Still not resolved. These styles need 
a) bugfix. Try loading a long list of beers, scrolling to the bottom of the page and click outside. 
b) moving to layout__side-menu. These are positioning styles. It is parent's responsibility to provide a layer for SideMenuBlock. SideMenuBlock should just render 100% of width and height of this layer.

2022-03-30 21:18 UTC, anton-matseichyk commented on src/containers/sideMenu/SideMenuBlock.jsx
> +        <SideMenu className={className}/>
BEM elements work only for immediate children, not drilling to grandchildren

2022-03-30 21:18 UTC, anton-matseichyk commented on src/containers/sideMenu/SideMenu.jsx
> +  <div className={`side-menu ${className}`} onClick={(e)=> e.stopPropagation()}>
Will discuss that tomorrow

2022-03-31 16:08 UTC, merged